jaffle_shop:
   target: databricks_job
   outputs:
     databricks_job:
      catalog: null
      type: databricks
      method: http
      schema: default
      host: adb-7666885566467644.4.azuredatabricks.net
      http_path: sql/protocolv1/o/7666885566467644/0115-063236-p6gl1yq
      token: "{{ env_var('DBT_ACCESS_TOKEN') }}"